### ISSUE TITLE
Failed to build gem native extension

### ISSUE THREAD

**Issue by gamaspecial** [gamaspecial/wiki#2]
```

D:\workspace\ruby\rails>gem install rails
Fetching i18n-1.8.10.gem
Fetching zeitwerk-2.4.2.gem
Fetching tzinfo-2.0.4.gem
Fetching concurrent-ruby-1.1.8.gem
Fetching minitest-5.14.4.gem
Fetching rack-2.2.3.gem
Fetching rack-test-1.1.0.gem
Fetching activesupport-6.1.3.1.gem
Fetching rake-13.0.3.gem
Successfully installed concurrent-ruby-1.1.8
Successfully installed i18n-1.8.10
Successfully installed tzinfo-2.0.4
Successfully installed zeitwerk-2.4.2
Successfully installed minitest-5.14.4
Successfully installed activesupport-6.1.3.1
Successfully installed rack-2.2.3
Successfully installed rack-test-1.1.0
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/racc-1.5.2/ext/racc/cparse
C:/tools/ruby26/bin/ruby.exe -I C:/tools/ruby26/lib/ruby/2.6.0 -r ./siteconf20210403-6660-pmisnl.rb extconf.rb
checking for rb_ary_subseq()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/tools/ruby26/bin/$(RUBY_BASE_NAME)
C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:1069:in `block in have_func'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from C:/tools/ruby26/lib/ruby/2.6.0/mkmf.rb:1068:in `have_func'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/tools/ruby26/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/racc-1.5.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/racc-1.5.2 for inspection.
Results logged to C:/tools/ruby26/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/racc-1.5.2/gem_make.out
```

**Comment by gamaspecial** [comment]
１．
```
D:\workspace\ruby\rails>gem uninstall -I -a -x --user-install --force
Successfully uninstalled activesupport-6.1.3.1
Successfully uninstalled bundler-2.2.15
Successfully uninstalled concurrent-ruby-1.1.8
Successfully uninstalled did_you_mean-1.3.0
Successfully uninstalled i18n-1.8.10
Successfully uninstalled minitest-5.11.3
Successfully uninstalled net-telnet-0.2.0
Successfully uninstalled power_assert-1.1.3
Removing rackup
Successfully uninstalled rack-2.2.3
Successfully uninstalled rack-test-1.1.0
Successfully uninstalled rake-13.0.3
Removing rake
Successfully uninstalled rake-12.3.2
Successfully uninstalled test-unit-3.2.9
Successfully uninstalled tzinfo-2.0.4
Successfully uninstalled xmlrpc-0.3.0
Successfully uninstalled zeitwerk-2.4.2
INFO:  Uninstalled all gems in
```
